### PR TITLE
Fix BC break in Document model

### LINKED ISSUE #89: BC break on Document Interface
I just discovered this BC break: https://github.com/worldia/textmaster-api/commit/f5d5406071cc12448628a086f374dbdd1adb38cd#diff-d3179b73f6b85e5745d088251b1e9fd3R192

As this project is an API useable by many project, this kind of BC break should be avoided or at least documented.

### PR DESCRIPTION
**Pull request by Pitoune**
Fix #89

### CODE REVIEW

File: lib/Textmaster/Model/Document.php [hunk 1]
```diff
@@ -206,6 +206,19 @@ public function getSourceContent()
...
      * {@inheritdoc}
      */
+    public function getTranslatedContent()
+    {
+        $authorWork = $this->getProperty('author_work');
+        if (self::TYPE_STANDARD === $this->getType() && !empty($authorWork)) {
+            return $authorWork['free_text'];
+        }
+
+        return $this->formatTranslatedContent();
```
Comment (jmleroux) [inline lib/Textmaster/Model/Document.php]: As it is deprecated, it think that the content of this method could be replaced just by
```
return $this->getSourceContent();
```

The main point of a BC is when a method is totally removed from an interface. Changing what the method is not à BC break.
